WITH RECURSIVE GENERATIONS AS (
    -- 1. 1세대: PARENT_ID가 NULL인 개체
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 2. 재귀적으로 세대 확장
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATIONS G ON E.PARENT_ID = G.ID
)

-- 3. 각 세대별 자식이 없는 개체의 수 카운트
SELECT COUNT(*) AS COUNT, G.GENERATION AS GENERATION
FROM GENERATIONS G
LEFT JOIN ECOLI_DATA CHILD ON G.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;
