SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM (
    SELECT
    ID,
    FISH_TYPE,
    LENGTH,
    MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO
) AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = I.MAX_LENGTH AND I.LENGTH IS NOT NULL
ORDER BY I.ID ASC