SELECT 
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT AS F1
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT AS F2
        WHERE F2.CATEGORY = F1.CATEGORY
    )
GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY PRICE DESC;