SELECT
    CASE
        WHEN MAX(S.CATEGORY = 'Front End' )
             AND MAX(S.NAME = 'Python') THEN 'A'
        WHEN MAX(S.NAME = 'C#' ) THEN 'B'
        WHEN MAX(S.CATEGORY = 'Front End') THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S
ON D.SKILL_CODE & S.CODE > 0
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC;
